# Generated by Django 4.1 on 2023-03-17 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_public', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uuid_private', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('avatar', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=users.models.DeviceType(1), enum_class=users.models.DeviceType, max_length=3)),
                ('wifi_name', models.CharField(max_length=250)),
                ('wifi_password', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='users.profile')),
            ],
            options={
                'verbose_name': 'Девайс',
                'verbose_name_plural': 'Девайсы',
            },
        ),
    ]
