# Generated by Django 4.1 on 2023-03-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwarePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('programm', models.FileField(blank=True, upload_to='media/programs/%Y/%m/%d')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='users.device')),
            ],
        ),
    ]
