# Generated by Django 4.1 on 2023-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmwareprograms',
            name='success',
        ),
        migrations.AddField(
            model_name='firmwareprograms',
            name='status',
            field=models.TextField(default='loading'),
        ),
        migrations.AlterField(
            model_name='firmwareprograms',
            name='programm',
            field=models.FileField(blank=True, upload_to='programs/%Y/%m/%d'),
        ),
    ]
